### ISSUE TITLE
Identifying retracted CMIP6 data in the Zarr holdings and removing them

### ISSUE THREAD

**Issue by matthew-mizielinski** [pangeo-data/pangeo-cmip6-cloud#30] opened 2022-01-27 14:47 UTC
Hi,

As mentioned at the last meeting there is a certain amount of Met Office data that I have retracted from the CMIP6 project on ESGF that is listed as available in the Pangeo cloud Zarr holdings on AWS (I have not checked the Google cloud listings).  There are a range of reasons why we have retracted data,  from [faulty coordinate information](https://errata.es-doc.org/static/view.html?uid=306c5df5-de28-9a5d-a9d3-46b41ad7a76f) to issues with the setup of the models, e.g. [faulty ancillary input files in some UKESM1 simulations](https://errata.es-doc.org/static/view.html?uid=5e70c479-9b19-ca91-a9ba-d11febe15377).

While I could provide a list of all datasets with the institution id "MOHC" that I have retracted, I know this could miss data published by other institutions, so I've put together an example of how you could iterate over all datasets to (a) look for connected Errata and (b) attempt to look up the status of datasets on ESGF via the handle service.

[Link to demonstration notebook](https://gist.github.com/matthew-mizielinski/db36dd2422148b0d39388295360c1228)

Note that this method of querying the Errata service, and then the handle service, depends on Errata being issued by the modelling groups that own the data, and there are likely some gaps (i.e. retracted datasets for which there is not a corresponding errata entry).  The existence of an errata does not indicate whether affected data has been retracted; there are `wont-fix` errata which detail an issue that the modelling group does not intend to address or does not require the retraction of data, e.g. [minor metadata issues](https://errata.es-doc.org/static/view.html?uid=7852f8b5-5be6-245e-a9f1-e8f866fe862f) and [the extension of datasets in time](https://errata.es-doc.org/static/view.html?uid=c532bcaf-59bd-19fc-9f98-f4230fbe141a).  The method I've used in the example code linked above is not necessarily the quickest or most efficient. If you have access to the files themselves and the `tracking_id` field from within the global attributes then a similar method could be applied that does not rely on the Errata service.

I am particularly keen, given the popularity of this service, that the status of data presented here is consistent with that in the CMIP6 archives served by ESGF. Let me know if there is any further information that would be helpful here, and please point me in the appropriate direction if this is not the best place for this request.

Matt Mizielinski
Climate Data Delivery Manager, Met Office Hadley Centre 
WGCM Infrastructure Panel co-chair

**Comment by rabernat** [comment] 2022-01-27 14:58
Matt this is a great place for the request. Thanks a lot for your helpful comments. I agree completely with everything you say. 

We used to have a (semi-manual) process in place for removing retracted data. But the person who managed it has retired. (Pinging @naomi-henderson with no expectation that she will reply.) So we need to transition to a more automated system.

@jbusecke - do you see a way to take @matthew-mizielinski's notebook and turn it into a cron job we can run with github workflows?

**Comment by matthew-mizielinski** [comment] 2022-01-27 15:05
Thanks Ryan,

If you do start sending large numbers of queries to the Errata and Handle services through code such as this do let me know -- I'd like to keep the developers of those systems in the loop so that they can look at how well their services are coping with the traffic (I've no idea whether what will be needed here is a large amount of traffic or just a drop in the ocean to those services, but might be worth checking).

**Comment by rabernat** [comment] 2022-01-27 15:15
> If you have access to the files themselves and the `tracking_id` field from within the global attributes then a similar method could be applied that does not rely on the Errata service.

Fortunately our archive does keep track of the `tracking_id`s that went into each Zarr

> The original datasets, stored in the WCRP/CMIP6 ESGF repositories, consist of netCDF files. Each of these datasets typically corresponds to a single variable saved at specified time intervals for the length of a single model run. For convenience, these datasets were often divided into multiple netCDF files. Our Zarr data stores correspond to the result of concatenating these netCDF files and then storing them as a single Zarr object. All of the metadata in the original netCDF files has been preserved, including the licensing information and the CMIP6 persistent identifiers (tracking_ids) which are unique for each of the original netCDF files.

https://pangeo-data.github.io/pangeo-cmip6-cloud/overview.html#zarr-storage-format

**Comment by naomi-henderson** [comment] 2022-01-27 16:56
@matthew-mizielinski @jbusecke and @rabernat , I thought I would also mention that I had not been actually removing datasets from zarr storage which have issues filed through the Errata Service.  They only get removed from the main CSV catalog file.  There is a separate catalog file, `gs://cmip6/cmip6-zarr-consolidated-stores-noQC.csv` (noQC meaning no quality control), which DOES still list the datasets with filed errata issues.  This is so that folks who have used the datasets prior to the filing of an errata issue can still reproduce and understand their old results.  If the datasets disappear there is no way to do forensics on old results ...

**Comment by rabernat** [comment] 2022-01-27 16:58
Hi Naomi! Thanks for chiming in from retirement-world! 😉  Sorry to be pestering you with CMIP6-related stuff, but your experience is so helpful.

Could you explain **how** you had been removing datasets from the catalog? What was your process for querying the errata and cross referencing it with the catalog? Any links to notebooks or scripts would be so helpful.

**Comment by naomi-henderson** [comment] 2022-01-27 17:36
Yes, though it is a little complicated. 

In [ESDOC](https://github.com/naomi-henderson/cmip6collect2/tree/main/ESDOC) there is a notebook which attempts to explain the half-automatic way I used to query the Errata Service and update lists of issues.  I was using the `esgissue` command from the [`esdoc-errata-client`](https://github.com/ES-DOC/esdoc-errata-client.git) package to get all of the current issues.  Then the notebook parses the issues as best it can, producing the `csv/ES-DOC_issues.csv` file for use in generating the catalog, see [MakeCloudCat_GC.ipynb](https://github.com/naomi-henderson/cmip6collect2/blob/main/MakeCloudCat_GC.ipynb).  As with all CMIP6 topics, there are many complicating factors, but that is the basic idea ....

So I generate TWO CSV catalogs, one which skips any datasets with `serious` issues (a very fuzzy definition should be in the notebook) when generating the main catalog and another which has all of the datasets with 3 extra columns added which  list the `status`, `severity` and `issue_url` for each dataset.  For example, one line in the CSV file is:

```
HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,tasmin,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/highresSST-present/r1i1p1f1/Amon/tasmin/gn/v20170706/,,20170706,wontfix,medium,https://errata.es-doc.org/static/view.html?uid=9b40a054-21a7-5ae7-a3eb-8c373c5adddc
```

which indicates that the zarr store `gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/highresSST-present/r1i1p1f1/Amon/tasmin/gn/v20170706/` has an issue with status='wontfix' and severity='medium' which can be checked at `https://errata.es-doc.org/static/view.html?uid=9b40a054-21a7-5ae7-a3eb-8c373c5adddc`

**Comment by jbusecke** [comment] 2022-01-28 01:53
Hi @naomi-henderson thank you so much. I like the approach of having a 'raw' catalog, which then gets 'masked' for the users.

Let me try to give an update on what I have found today, where I might need some help, and my plans going forward.

Some nomenclature:
- `dataset` A datasets concatenated in time, equivalent to a zarr store in the cloud holdings. The smallest unit of data we have in this catalog.

- `raw_catalog` the `no_qc` catalog @naomi-henderson mentioned, with everything that was ever uploaded.

- `public_catalog` the 'masked' catalog which is exposed to the public.

**Central identification of datasets**
An important aspect here and for other aspects of working with these datasets is the ability to uniquely identify a dataset. It seems that a `dataset_id` ( in the form of `activityid.institute_id.source_id.experiment_id.variant_label.table_id.variable_id.grid_klabel.version`) does that job. From @matthew-mizielinski s notebook it seems like this is sufficient to query errata. This signature is conveniently also our zarr store name. Any objections to using these as unique identifiers of a dataset?

**How to identify retractions**
Thanks to @matthew-mizielinski I think I have a good idea what I need to implement to identify retracted datasets. I have been experimenting with grabbing the handle_id values directly from our zarr stores (instead of querying errata which is quite slow), and this seems to work well! I was able to identify all the retracted datasets from @matthew-mizielinski s example, and some others! I will clean up that code and run it over the full catalog soon. 

**How to delete/mask the found datasets**
But first I would like to discuss how we go about the 'deactivation' of the datasets that we identified above?
My suggestion (happy to adjust) is the following:
1. I will set up python code that runs on a github action, scans the full catalog and produces a list of `dataset_ids` reflecting the most up to date retractions. 
2. I would then try to adopt @naomi-henderson s approach and run an action that creates a 'filtered' catalog, where we simply omit the datasets that are retracted from the updated `public_catalog`.

We could implement some sort of check, where a maintainer has to 'sign off' on newly added retractions, or hope that everything is going to work out fine 😜.

I think this approach is generally better than deleting the stores (we can talk about that elsewhere) in case something does go wrong it seems easier to recreate a csv file than reupload data.

**Retracted vs issues**
A connected issue here is the question of how much 'quality control' we want to do for the user here. I think removing retractions is obvious, but I think @naomi-henderson had removed even some other datasets with issues? Any suggestions for a heuristic what 'goes public' and what doesnt?

I personally would favor an approach where we remove as little as possible and maybe implement some functionality on a higher level (e.g. cmip6_pp) where the user could check for issues on a dataset basis (using some of the logic use here). But maybe there is a good reason not to do this.

**More general Questions**
- Somewhere in the pipeline the facet `variant_label` has been renamed to `member_id`. This has given me quite the headache over at [cmip6_preprocessing](https://github.com/jbusecke/cmip6_preprocessing/blob/209041a965984c2dc283dd98188def1dea4c17b3/cmip6_preprocessing/postprocessing.py#L180), and I still have not been able to understand why this was introduced. Going forward, are we going to carry this depth or opt for a new catalog, which is organized strictly by facet names which are also used in the dataset attributes.
- Uncertainty in version number due to time concatenation. What do we do if only a subset of files from a zarr store are retracted? I guess for now we have to remove the store if `any` of them is bad. In the future we might want to think about an automatic retrigger mechanism that would try to rebuild that dataset specific store.  


Thats it for today. Ill try to work on this early next week again.

**Comment by matthew-mizielinski** [comment] 2022-01-28 15:01
Some thoughts here.

I fully understand the desire to keep data that might have been used -- I still have a copy of all Met Office data that I have retracted from the CMIP6 archive for the same reasons.  Note that ESGF does not do this; when a retraction is run the data files are removed but the records in the index remain (the cost of retaining this data is likely a contributing factor for this policy). Handling retractions through "de-listing" data sets in the catalogues is one way, another might be to relocate such data to a "retracted" directory location, but this almost certainly has additional complications.  Not deleting the data also gives you the chance to easily correct any mistakes rather than having to re-download and reprocess.

The Errata service provides valuable information on a range issues, but the simple existence of one connected with a dataset doesn't mean that the data is faulty (see some of the examples above). In your situation, if you have the flexibility to extend the global attributes on Zarr datasets, I would be tempted to add a field such as `"connected_errata": []` with a list of links back to the errata system*. This is something we cannot do with netCDF files on ESGF.

Regarding the first of @jbusecke's questions:
In case this helps clarify how the [global attributes](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk) are intended to be used in CMIP6 (apologies if I'm misunderstanding the question above): in the vast majority of cases the `member_id` is identical to the `variant_label`. The one case where this is not true is for the ensemble experiments in DCPP. If you search for the experiment `dcppA-hindcast` in the [CMIP6 Experiment id list](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) you'll see that it has a range of valid `sub_experiment_id` values relating to start dates of the hindcast.  This is expressed in the dataset id / directory / file name structure by using `<sub_experiment_id>-<variant_label>` instead of `<variant_label>`. While the default `sub_experiment_id` of `none` could have been used in this facet of the nomenclature I suspect that it was felt that this wasn't particularly elegant.

If you do manage to produce a list of MOHC datasets from your Zarr store that have been retracted, feel free to point me at it for verification -- I can quickly compare this back to my inventory database as a sanity check.



*should you consider this there might be other valuable attributes that could be added (e.g. DOIs and citation service links), but I think this is a separate conversation

**Comment by jbusecke** [comment] 2022-01-28 21:07
> The one case where this is not true is for the ensemble experiments in DCPP. 

Thanks for the explanation @matthew-mizielinski. I will have to take that into account in cmip6_pp. 

A clarification question: What would a unique `dataset_id` for a `dcppA-hindcast` run look like? 
More generally, is this sort of id 
```
activityid.institute_id.source_id.experiment_id.variant_label.table_id.variable_id.grid_klabel.version
```
unique for all CMIP experiments?

**Comment by matthew-mizielinski** [comment] 2022-01-31 10:18
A couple of examples, with breakdowns of individual facets:

instance_id = `CMIP6.DCPP.NCAR.CESM1-1-CAM5-CMIP5.dcppA-hindcast.s1964-r29i1p1f1.Amon.psl.gn.v20191007`
mip_era = CMIP6
activity_id = DCPP
institution_id = NCAR
source_id = CESM1-1-CAM5-CMIP5
experiment_id = dcppA-hindcast
member_id = s1964-r29i1p1f1  (sub_experiment_id = s1964, variant_label = r29i1p1f1)
table_id = Amon
variable_id = psl
grid_label = gn  (native grid)
version = v20191007

instance_id = `CMIP6.DCPP.CNRM-CERFACS.CNRM-CM6-1.dcppC-amv-neg.r21i1p1f2.AERmon.toz.gr.v20190620`
mip_era = CMIP6
activity_id = DCPP
institution_id = CNRM-CERFACS
source_id = CNRM-CM6-1
experiment_id = dcppC-amv-neg
member_id = variant_label = r21i1p1f2
table_id = AERmon
variable_id = toz
grid_label = gr (implies regridded data)
version = v20190620

I would suggest using the full id (referred to as the instance_id in several places on ESGF, the dataset_id is the part without the version*) as your key here. Note that there are projects in the works beyond CMIP6, where a different mip_era would likely be used, so keeping the mip era is valuable.

*Apologies I may have misused `dataset_id` above.

**Comment by jbusecke** [comment] 2022-01-31 14:37
Thanks for the clarification, that is super helpful information to have.

**Comment by jbusecke** [comment] 2022-02-19 00:58
Some additional considerations that I forgot to mention: 
There seems to be some 'flakyness' to the esgf query. I have found instances where the retrieved number of instance_ids is not equal to the items found in the response header. I currently error out the script if that happens, but it would be nice to give it a couple of retries (which I found usually resolve the issue).

**Comment by jbusecke** [comment] 2022-02-19 21:39
Ah thanks @durack1, ill def give that a try!

**Comment by rabernat** [comment] 2022-02-20 22:53
Julius huge 👏👏👏 for pushing forward to a simple and effective solution to this important problem. Excellent work!

In the long term, I think we want to move to a scenario where we are storing our authoritative catalog in Google BigQuery and generating the CSV periodically (daily?) from that.

In the short term, you probably want to:
1. Generate a new catalog csv
2. Run some sort of sanity checks on it
3. Replace the old catalog with the new one

**Comment by jbusecke** [comment] 2022-02-21 15:45
100% agree that we need something more stable in the long term. I would suggest we talk about this after Ocean Sciences?

> Run some sort of sanity checks on it

Any ideas what to do there? Checking that we dont remove more than a certain % per run maybe?


@durack1 : I am running the action with the updated url [here](https://github.com/pangeo-data/pangeo-cmip6-cloud/actions/runs/1877068919)

**Comment by jbusecke** [comment] 2022-02-21 15:47
> @durack1 : I am running the action with the updated url [here](https://github.com/pangeo-data/pangeo-cmip6-cloud/actions/runs/1877068919)

It definitely [works, and also seems faster](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5276664364?check_suite_focus=true). Time will tell if its more reliable 😜

**Comment by jbusecke** [comment] 2022-02-21 15:50
OH wait. So this is weird: 

From the [dkrz version](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5262384109?check_suite_focus=true) I get [8385 stores](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5262384109?check_suite_focus=true#step:6:62) to remove, but from the [llnl version](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5276664364?check_suite_focus=true) I only get [8264 stores](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5276664364?check_suite_focus=true#step:6:62).

Can somebody here help me understand the difference?

**Comment by durack1** [comment] 2022-02-21 16:06
> Any ideas what to do there? Checking that we dont remove more than a certain % per run maybe?

This is a tricky one, I've hit a bunch of issues in the past assuming things would work when they didn't. Polling multiple nodes, or having a tiered fail safe is a good idea (LLNL -> DKRZ -> CEDA), if there are inconsistencies, then ponder/pause as you may have uncovered an issue - any resulting actions may cause you even more headaches and a cleanup job

**Comment by jbusecke** [comment] 2022-02-21 18:31
That comment was more directed towards checking our internal csv I believe. But that comment makes me think:

What I could implement relatively easily is this:
- Poll several nodes (the three suggested by @durack1 for instance)
- Merge the results, and only take instance_ids that are present in all three nodes?
- Only retract these datasets from our catalog

**Comment by sashakames** [comment] 2022-02-22 14:57
> @sashakames, any ideas why the difference, dkrz > LLNL?

Strangely enough, I notice issues in our own retraction checking that the LLNL replica shard struggles to give full results for all the MOHC records. Not sure if thats the case here.  My general recommendation is to query the "home" index for a particular institution if performing bulk record retrieval, eg, for MOHC use the CEDA index with distrib=false.

**Comment by jbusecke** [comment] 2022-02-22 16:38
Hmm that makes it quite a bit more difficult. Is there a mapping from institute to index node available?

I could investigate some more which datasets are unique to which index, but not sure if that is helpful.

@sashakames do you think that the brute force approach (querying multiple nodes with distrib=true and finding the union of the results) has any downsides? E.g. do you expect some nodes to give retractions back falsely, or is it more likely that they are missing some retractions?

**Comment by aradhakrishnanGFDL** [comment] 2022-02-22 17:00
> 100% agree that we need something more stable in the long term. I would suggest we talk about this after Ocean Sciences?

@jbusecke Super helpful actions and issue thread. Since this actions workflow you have pioneered is also applicable for CMIP6 cloud data in AWS (zarr and netcdf), I do envision the sanity checkers and other utilities built around, will tremendously help with a uniform (collaborative, as intended) toolset to "lightly" maintain different CMIP6 buckets. 
I agree discussing the stable long-term workflow at the next ESGF/Pangeo cloud data working group call would be useful, building on what you have today. 

> 
> > Run some sort of sanity checks on it
> 
> Any ideas what to do there? Checking that we dont remove more than a certain % per run maybe?



The issues that Naomi notes as the "serious issues" which I assume may be impediments to generating a functioning zarr stores could be one of those critical checks in the sanity checker utility. 

E.g. identifying non-contiguous time in datasets? 

(I have also encountered bad DRS paths that have messed up the catalog generation process, which I now skip in the catalog generation process. ) 

I agree, it's important to document how far we should go with our automated sanity checkers versus expectations from users to run their own (or shared) comprehensive QA checks. I support the latter for the most part. 

This may be an overkill, but leaving info in the (old) CSV to indicate the issue (if queryable) may help, although one could also query the errata service with the datasetID or something and get info at a later date. I vaguely recollect Naomi used to document the issues. 

> 
> @durack1 : I am running the action with the updated url [here](https://github.com/pangeo-data/pangeo-cmip6-cloud/actions/runs/1877068919)

**Comment by jbusecke** [comment] 2022-02-22 18:00
Thanks for the comments @aradhakrishnanGFDL. Just to clarify something here: My current `source` catalog is already the 'quality controlled' version created by Naomi. I did it this way, so I can for now retract datasets without thinking about that logic, but I agree that point will need some more discussion.

**Comment by jbusecke** [comment] 2022-02-22 18:11
So i spent some time to find out which instance_ids are different for querying differnt index nodes. 

The notebook can be found [here](https://gist.github.com/jbusecke/7ed565ae29deaddcc4f3453944d0bc87).

Bottom line of this is that, when comparing DKRZ and LLNL, there are instance_ids that are unique to **each** node. 

So it seems useful to query as many nodes as possible, and then merge the resulting lists (as 'outer'), or is there an issue with this approach?

**Comment by sashakames** [comment] 2022-02-22 18:19
@jbusecke Probably you could work with "brute-force" approach for querying multiple and reconciling differences.   I don't see the source to the "query_retractions" method so I can't say if there's anything problematic there.

**Comment by matthew-mizielinski** [comment] 2022-02-23 12:47
@jbusecke, looks like good progress is being made here, should it be useful to have what I think is the full MOHC list then have a look [here](https://gist.github.com/matthew-mizielinski/b0aa016ce52584fccd3ad866bb6834e9) -- this should be all the MOHC datasets that you have that I have retracted.

**Comment by jbusecke** [comment] 2022-02-23 15:04
@sashakames: Sorry for that. I somewhat silently refactored that into [this module](https://github.com/pangeo-data/pangeo-cmip6-cloud/blob/master/retractions.py).

**Comment by jbusecke** [comment] 2022-02-23 15:07
Thanks @matthew-mizielinski, Ill see if I can compare this to the output I get. 

If I am doing this with multiple nodes, I might aswell query all of them. Is there a list of urls for all nodes available somewhere? @durack1

**Comment by jbusecke** [comment] 2022-02-23 18:13
Ok it is done 🤗

~8k stores were removed from our catalog [here](https://github.com/pangeo-data/pangeo-cmip6-cloud/actions/runs/1888908356). 
Running the action again confirms that we now have a catalog containing [0 retractions](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5308085911?check_suite_focus=true#step:6:43). 

I will enable the dkrz node now and see if that yields some more retractions.

@matthew-mizielinski I also have manually confirmed that all the instance_ids you provided are marked as retracted!

Thanks everyone for the great help with this! I feel really good going into OSM with a properly maintained catalog.

**Comment by jbusecke** [comment] 2022-02-23 18:21
Still on the agenda: 
- Adapt the current script to the AWS zarr mirror
- Add more nodes

**Comment by aradhakrishnanGFDL** [comment] 2022-02-23 18:26
Quick comment about nodes to query, the CMIP6 data citation landing pages point to DKRZ and LLNL nodes. To me, this implies 99% completeness, perhaps. More of a comment only.

**Comment by durack1** [comment] 2022-02-23 20:01
> Is there a list of urls for all nodes available somewhere? @durack1

The nodes that are "tier 1" include:
https://esgf-node.llnl.gov/search/cmip6/
https://esgf-data.dkrz.de/search/cmip6-dkrz/
https://esgf-index1.ceda.ac.uk/search/cmip6-ceda/
An additional which is normally reliable https://esgf-node.ipsl.upmc.fr/search/cmip6-ipsl/

These are all listed on https://esgf-node.llnl.gov/projects/cmip6/

**Comment by jbusecke** [comment] 2022-02-23 20:23
Fantastic. Exactly what I was looking for @durack1.

**Comment by durack1** [comment] 2022-03-01 15:54
@jbusecke nice! Do you have some diagnostic out from the LLNL/DKRZ/CEDA/IPSL index scour that points out inconsistencies? It'd be nice to know about problems appearing before they causes issues

**Comment by jbusecke** [comment] 2022-03-01 17:50
@durack1 at the moment I am only displaying the [number of retractions found per node](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5379575040?check_suite_focus=true#step:6:17), which could be used as a very rough consistency check each time. 

I certainly could implement some more logic [here](https://github.com/pangeo-data/pangeo-cmip6-cloud/blob/d246eb6b684e6ee42f93e87d55dc3ec90c105173/create_filtered_catalog.py#L38-L40) to identify the retractions that are unique to each node (is that the info you would be after?). 

If that would be of help, I could also set this sort of stuff up in a separate action, and keep track of how these evolve over time. Happy to implement anything that could help upstream!

**Comment by durack1** [comment] 2022-03-01 18:52
@jbusecke I wonder how flexible github actions are, if there was an index inconsistency (which appears to be a common problem) then maybe you could fling an email with these stats (this might be useful https://github.com/marketplace/actions/send-email) alerting of an issue rather than having to remind yourself to check

**Comment by jbusecke** [comment] 2022-03-03 00:09
@durack1 I have implemented this in the current script: 
The logs identify the number of missing instance_ids on each node (see [here](https://github.com/pangeo-data/pangeo-cmip6-cloud/runs/5400054938?check_suite_focus=true#step:6:96) for example), and also create an [artifact](https://github.com/pangeo-data/pangeo-cmip6-cloud/actions/runs/1925278740) that contains a csv per node with only the missing ones in them.

**Comment by durack1** [comment] 2022-03-11 00:47
@jbusecke this is great! Are you running this as a cronjob/repeated service? I wonder if inconsistencies are common, or whether these are more uncommon, knowing the answer to this question would be good before figuring out what to do with it

**Comment by jbusecke** [comment] 2022-03-16 22:22
@durack1 yes this is run daily at night EST. I just checked and the last 6 times were successful (you somehow mentioned it into working lol). Please check the results out here: https://github.com/pangeo-data/pangeo-cmip6-cloud/actions

**Comment by jbusecke** [comment] 2024-01-30 17:03
All of this logic was overhauled and now lives [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/scripts/retraction.py).

**Closed by jbusecke** 2024-01-30 17:03 UTC
